// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DevolverArchivoSubir() {
  return window['go']['main']['App']['DevolverArchivoSubir']();
}

export function DevolverCodigoQr(arg1, arg2) {
  return window['go']['main']['App']['DevolverCodigoQr'](arg1, arg2);
}

export function DevolverEliminarRegistro(arg1, arg2, arg3) {
  return window['go']['main']['App']['DevolverEliminarRegistro'](arg1, arg2, arg3);
}

export function DevolverRegistros() {
  return window['go']['main']['App']['DevolverRegistros']();
}

export function DevolverSubida(arg1) {
  return window['go']['main']['App']['DevolverSubida'](arg1);
}
