// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modelos} from '../models';

export function DevolverArchivoSubir():Promise<string>;

export function DevolverCodigoQr(arg1:string,arg2:number):Promise<string>;

export function DevolverEliminarRegistro(arg1:number,arg2:string,arg3:string):Promise<Error>;

export function DevolverRegistros():Promise<modelos.Coleccion>;

export function DevolverSubida(arg1:string):Promise<modelos.Registro>;
